### PR TITLE
Fix the build on GHC 8.6, 8.4 and 7.8

### PR DESCRIPTION
**Pull request by gwils**

### CODE REVIEW

**Comment by timbod7** [comment]
Thanks for the patch. The only problem is that we at helix are still using lts-10.10, which includes ghc 8.2.2.  I assume these changes won't compile for 8.2?

**Comment by gwils** [comment]
For me these changes compile from GHC 8.6 back to GHC 7.8, including 8.2.2.
It would be worthwhile checking out this branch for yourself and compiling with stack and lts-10.10, but I'm almost certain they should be fine.

**Comment by o1lo01ol1o** [comment]
Any update on this?

**Comment by timbod7** [comment]
We are not using this any more - we've replaced the haskell code with typescript, which we find is more expressive for infrastructure definitions.

**Pull request merged**
